### PR TITLE
updating files to build ros package with rtab-map lib v0.20.3

### LINKED ISSUE #450: Rtabmap is not compatible with Ubuntu 18.04 PCL 1.11 in ROS melodic
My environment is Ubuntu 18.04, PCL 1.11. The code works with Ubuntu 16.04, PCL 1.8. Can you please confirm this bug?

The error pops up like following: 

/home/chaonew/catkin_ws/src/rtabmap_ros/src/OdometryROS.cpp: In member function ‘void rtabmap_ros::OdometryROS::processData(const rtabmap::SensorData&, const ros::Time&)’:
/home/chaonew/catkin_ws/src/rtabmap_ros/src/OdometryROS.cpp:735:45: error: call of overloaded ‘PointXYZRGB(int, int, int)’ is ambiguous
     pcl::PointXYZRGB pt(inlier?0:255, 255, 0);
                                             ^
In file included from /usr/local/include/pcl-1.11/pcl/point_types.h:349:0,
                 from /usr/local/include/pcl-1.11/pcl/common/impl/copy_point.hpp:40,
                 from /usr/local/include/pcl-1.11/pcl/common/copy_point.h:58,
                 from /usr/local/include/pcl-1.11/pcl/common/impl/io.hpp:44,
                 from /usr/local/include/pcl-1.11/pcl/common/io.h:587,
                 from /usr/local/include/pcl-1.11/pcl/io/file_io.h:41,
                 from /usr/local/include/pcl-1.11/pcl/io/pcd_io.h:45,
                 from /home/chaonew/catkin_ws/src/perception_pcl/pcl_conversions/include/pcl_conversions/pcl_conversions.h:70,
                 from /home/chaonew/catkin_ws/src/rtabmap_ros/src/OdometryROS.cpp:35:
/usr/local/include/pcl-1.11/pcl/impl/point_types.hpp:641:12: note: candidate: pcl::PointXYZRGB::PointXYZRGB(float, float, float)
     inline PointXYZRGB (float _x, float _y, float _z):
            ^~~~~~~~~~~
/usr/local/include/pcl-1.11/pcl/impl/point_types.hpp:638:12: note: candidate: pcl::PointXYZRGB::PointXYZRGB(uint8_t, uint8_t, uint8_t)
     inline PointXYZRGB (std::uint8_t _r, std::uint8_t _g, std::uint8_t _b):
            ^~~~~~~~~~~
rtabmap_ros/CMakeFiles/rtabmap_ros.dir/build.make:110: recipe for target 'rtabmap_ros/CMakeFiles/rtabmap_ros.dir/src/OdometryROS.cpp.o' failed
make[2]: *** [rtabmap_ros/CMakeFiles/rtabmap_ros.dir/src/OdometryROS.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:8378: recipe for target 'rtabmap_ros/CMakeFiles/rtabmap_ros.dir/all' failed
make[1]: *** [rtabmap_ros/CMakeFiles/rtabmap_ros.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

                                             ^

### PR DESCRIPTION
**Pull request by mirellameelo**
Hi. While following the README in the "ros2" branch I faced two issues. The first one regards the PCL version. For PCL version equals or greater than 10.1, the change made in 'src/OdometryROS.cpp' is necessary, which is the same modification made to fix #450 but in the "melodic" branch. Second, the latest version of RTAB-LIB (v0.20.3) has changed the variable type of the method 'graph::findNearestNodes', which justifies the modification made in 'src/CoreWrapper.cpp' (please refer to #470).
After these changes, I could successfully build RTAB-LIB ROS2 (Eloquent) package. I appreciated if you could check it! 

Thanks!

### CODE REVIEW

**Comment by matlabbe** [comment]
Thank you! my mistake I didn't test the ros2 branch with latest changes from the library.

**Comment by mirellameelo** [comment]
@matlabbe thanks for the reply! I was able to build it, but when I run it I got "double free or corruption". Please refer to #472
I really appreciate it if you could help me with that. Thanks!
