### ISSUE TITLE
Build Error: The plugin for class 'rtabmap_ros/MapCloud' failed to load.  Error: According to the loaded plugin descriptions the class rtabmap_ros/MapCloud with base class type rviz::Display does not exist.

### ISSUE THREAD

**Issue by julianraheema** [introlab/rtabmap_ros#1113]
I used to have an old rtabmap_ros package, and it worked fine with ROS Noetic, ubuntu 20.04. I was doing SLAM, and I was getting 2D and 3D depth image maps just fine. Everything was working great. But I did apt update and upgrade, and the rtabmap stopped working :( . I thought it is time to update to the new rtabmap_ros since the old one is broken, so I followed the instructions at https://github.com/introlab/rtabmap_ros#build-from-source "build from source" to build inside my workspace, and switched to noetic-dev branch and succeeded build. Now when I launch the rtabmap, I get these errors, and I can't see the topics for MapGraph, MapCloud, and Info.

Please help!

SW
OS:20.04
ROS: Noetic
HW:
Velodyne 16 puck
RealSense 455

**old rtabmap_ros package:**
Build: Fails
Running: I don't know

![image](https://github.com/introlab/rtabmap_ros/assets/6541950/27d1e3bc-1899-4c78-a9f3-005d5c1b758d)
build error:

error: ‘class rtabmap::OccupancyGrid’ has no member named ‘addToCache’
  374 |      occupancyGrid_->addToCache(iter->first, ground, obstacles, emptyCells);
      |                      ^~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:379:21: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘addToCache’
  379 |     occupancyGrid_->addToCache(iter->first, jter->second.first.first, jter->second.first.second, jter->second.second);
      |                     ^~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp: In member function ‘std::map<int, rtabmap::Transform> MapsManager::updateMapCaches(const std::map<int, rtabmap::Transform>&, const rtabmap::Memory*, bool, bool, const std::map<int, rtabmap::Signature>&)’:
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:564:63: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  564 |       data = memory->getNodeData(iter->first, occupancyGrid_->isGridFromDepth() && !occupancySavedInDB, !occupancyGrid_->isGridFromDepth() && !occupancySavedInDB, false, true);
      |                                                               ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:564:122: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  564 |       data = memory->getNodeData(iter->first, occupancyGrid_->isGridFromDepth() && !occupancySavedInDB, !occupancyGrid_->isGridFromDepth() && !occupancySavedInDB, false, true);
      |                                                                                                                          ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:593:64: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  593 |        data = memory->getNodeData(iter->first, occupancyGrid_->isGridFromDepth(), !occupancyGrid_->isGridFromDepth(), false, false);
      |                                                                ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:593:100: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  593 |        data = memory->getNodeData(iter->first, occupancyGrid_->isGridFromDepth(), !occupancyGrid_->isGridFromDepth(), false, false);
      |                                                                                                    ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:596:25: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  596 |         occupancyGrid_->isGridFromDepth() && generateGrid?&rgb:0,
      |                         ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:597:25: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  597 |         occupancyGrid_->isGridFromDepth() && generateGrid?&depth:0,
      |                         ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:598:26: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  598 |         !occupancyGrid_->isGridFromDepth() && generateGrid?&scan:0,
      |                          ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:608:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘createLocalMap’
  608 |        occupancyGrid_->createLocalMap(tmp, ground, obstacles, emptyCells, viewPoint);
      |                        ^~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:630:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘parseParameters’
  630 |        occupancyGrid_->parseParameters(parameters);
      |                        ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:637:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  637 |        occupancyGrid_->isGridFromDepth() && generateGrid?&rgb:0,
      |                        ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:638:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  638 |        occupancyGrid_->isGridFromDepth() && generateGrid?&depth:0,
      |                        ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:639:25: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘isGridFromDepth’
  639 |        !occupancyGrid_->isGridFromDepth() && generateGrid?&scan:0,
      |                         ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:649:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘createLocalMap’
  649 |        occupancyGrid_->createLocalMap(tmp, ground, obstacles, emptyCells, viewPoint);
      |                        ^~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:665:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘parseParameters’
  665 |        occupancyGrid_->parseParameters(parameters);
      |                        ^~~~~~~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:679:24: error: ‘class rtabmap::OccupancyGrid’ has no member named ‘addToCache’
  679 |        occupancyGrid_->addToCache(iter->first, mter->second.first.first, mter->second.first.second, mter->second.second);
      |                        ^~~~~~~~~~
/home/spot/src/spot_autonomy_baseline/src/rtabmap_ros/src/MapsManager.cpp:698:18: error: ‘class rtabmap::OctoMap’ has no member named ‘addToCache’
  698 |        octomap_->addToCache(iter->first, mter->second.first.first, mter->second.first.second, mter->second.second, pter->second);
      |                  ^~~~~~~~~~

New rtabmap_ros
![image](https://github.com/introlab/rtabmap_ros/assets/6541950/ccc5ab0c-0364-4daa-8138-c218940acf9d)

Builds: OK
Running: I have this error below

[ERROR] [1706580783.874992568]: PluginlibFactory: The plugin for class 'rtabmap_ros/MapCloud' failed to load.  Error: According to the loaded plugin descriptions the class rtabmap_ros/MapCloud with base class type rviz::Display does not exist. Declared types are  grid_map_rviz_plugin/GridMap octomap_rviz_plugin/ColorOccupancyGrid octomap_rviz_plugin/OccupancyGrid octomap_rviz_plugin/OccupancyGridStamped octomap_rviz_plugin/OccupancyMap octomap_rviz_plugin/OccupancyMapStamped rtabmap_rviz_plugins/Info rtabmap_rviz_plugins/MapCloud rtabmap_rviz_plugins/MapGraph rviz/AccelStamped rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/TwistStamped rviz/WrenchStamped rviz_imu_plugin/Imu rviz_map_plugin/ClusterLabel rviz_map_plugin/Map3D rviz_map_plugin/Mesh rviz_plugin_tutorials/Imu
[ERROR] [1706580783.875324607]: PluginlibFactory: The plugin for class 'rtabmap_ros/MapGraph' failed to load.  Error: According to the loaded plugin descriptions the class rtabmap_ros/MapGraph with base class type rviz::Display does not exist. Declared types are  grid_map_rviz_plugin/GridMap octomap_rviz_plugin/ColorOccupancyGrid octomap_rviz_plugin/OccupancyGrid octomap_rviz_plugin/OccupancyGridStamped octomap_rviz_plugin/OccupancyMap octomap_rviz_plugin/OccupancyMapStamped rtabmap_rviz_plugins/Info rtabmap_rviz_plugins/MapCloud rtabmap_rviz_plugins/MapGraph rviz/AccelStamped rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/TwistStamped rviz/WrenchStamped rviz_imu_plugin/Imu rviz_map_plugin/ClusterLabel rviz_map_plugin/Map3D rviz_map_plugin/Mesh rviz_plugin_tutorials/Imu
[ERROR] [1706580783.875424699]: PluginlibFactory: The plugin for class 'rtabmap_ros/Info' failed to load.  Error: According to the loaded plugin descriptions the class rtabmap_ros/Info with base class type rviz::Display does not exist. Declared types are  grid_map_rviz_plugin/GridMap octomap_rviz_plugin/ColorOccupancyGrid octomap_rviz_plugin/OccupancyGrid octomap_rviz_plugin/OccupancyGridStamped octomap_rviz_plugin/OccupancyMap octomap_rviz_plugin/OccupancyMapStamped rtabmap_rviz_plugins/Info rtabmap_rviz_plugins/MapCloud rtabmap_rviz_plugins/MapGraph rviz/AccelStamped rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/TwistStamped rviz/WrenchStamped rviz_imu_plugin/Imu rviz_map_plugin/ClusterLabel rviz_map_plugin/Map3D rviz_map_plugin/Mesh rviz_plugin_tutorials/Imu

**Comment by matlabbe** [comment]
You would have to update the rviz config by re-adding the rtabmap's related displays, or edit in text the rviz config and change all rtabmap_ros by rtabmap_rviz_plugins.

**Comment by matlabbe** [comment]
See also https://wiki.ros.org/rtabmap_ros#rtabmap_ros.2Fnoetic_and_newer.Migration_Guide_New_Interface_Noetic.2FROS2

The latest binaries and source code all use the new interface.

**Comment by julianraheema** [comment]
Thank you so much. It seems working now. I will test it some more and then close this ticket if everything looks fine. Much appreciated.

**Comment by julianraheema** [comment]
Tested and worked as expected. The proposed solved the problem. Thank you so much
